Use set difference to compare variants
PGScatalog/fraposa_pgsc pull request #6
Opened 2023-05-31 10:29 UTC by nebfield

Multiple variants at the same position may be in a different order

2023-05-31 10:39 UTC, smlmbrt requested changes
The order of the variants is important. We could do something where the target samples variants is reordered to match the first? Ideally the order would be identical from the plink outputs

2023-06-05 16:51 UTC, smlmbrt commented on fraposa_pgsc/fraposa.py
> +            W = W[variants.study_indexes]
We should probably reorder W_bim too for consistency?

2023-06-05 16:51 UTC, smlmbrt commented on fraposa_pgsc/fraposa.py
> +            W = W[variants.study_indexes]
Should this be explicitly for rows? E.g.:
`W = W[variants.study_indexes, :]`

2023-06-05 16:51 UTC, smlmbrt commented on fraposa_pgsc/fraposa.py
> +            ordered_stu_vars = sorted(stu_vars, key=ref_indexed.get)
Is this the same/redundant with `stu_indexed`?

2023-06-06 08:53 UTC, nebfield commented on fraposa_pgsc/fraposa.py
> +            ordered_stu_vars = sorted(stu_vars, key=ref_indexed.get)
`stu_indexed` is a list of indexes, while `ordered_stu_vars` is a list of variant identifiers. 

The variants class contains both because `stu_indexed` is used to re-order the bed file (a numpy array), and `ordered_stu_vars` is used to re-index the bim file (a pandas df).

I'll add a type hint to make it clearer 😄

2023-06-07 13:05 UTC, smlmbrt approved these changes

2023-06-07 13:05 UTC, merged